# Generated by Django 6.0 on 2025-12-26 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_company_pay_nds_company_tax_risk'),
    ]

    operations = [
        migrations.CreateModel(
            name='GosZakupCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('value', models.FloatField(verbose_name='Значение')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goszakupcustomer', to='companies.company', verbose_name='Компания')),
            ],
            options={
                'db_table': 'gos_zakup_customer',
            },
        ),
        migrations.CreateModel(
            name='GosZakupSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('value', models.FloatField(verbose_name='Значение')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goszakupsupplier', to='companies.company', verbose_name='Компания')),
            ],
            options={
                'db_table': 'gos_zakup_supplier',
            },
        ),
        migrations.CreateModel(
            name='Nds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('value', models.FloatField(verbose_name='Значение')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nds', to='companies.company', verbose_name='Компания')),
            ],
            options={
                'db_table': 'nds',
            },
        ),
        migrations.CreateModel(
            name='Taxes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('value', models.FloatField(verbose_name='Значение')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='taxes', to='companies.company', verbose_name='Компания')),
            ],
            options={
                'db_table': 'taxes',
            },
        ),
    ]
