# Generated by Django 6.0 on 2025-12-26 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_pay_nds_company_tax_risk'),
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goszakupcustomer',
            options={'verbose_name': 'Гос. закупки (как закупщик)', 'verbose_name_plural': 'Гос. закупки (как закупщик)'},
        ),
        migrations.AlterModelOptions(
            name='goszakupsupplier',
            options={'verbose_name': 'Гос. закупки (как поставщик)', 'verbose_name_plural': 'Гос. закупки (как поставщик)'},
        ),
        migrations.AlterModelOptions(
            name='nds',
            options={'verbose_name': 'НДС', 'verbose_name_plural': 'НДС'},
        ),
        migrations.AlterModelOptions(
            name='taxes',
            options={'verbose_name': 'Налоги', 'verbose_name_plural': 'Налоги'},
        ),
        migrations.AlterField(
            model_name='goszakupcustomer',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goszakupcustomer', to='companies.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='goszakupsupplier',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goszakupsupplier', to='companies.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='nds',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nds', to='companies.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='taxes',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxes', to='companies.company', verbose_name='Компания'),
        ),
    ]
