# Generated by Django 6.0 on 2025-12-23 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=1024, null=True, verbose_name='Название организации на русском')),
                ('name_kz', models.CharField(max_length=1024, null=True, verbose_name='Название организации на казахском')),
                ('register_date', models.DateField(null=True, verbose_name='Время создания организации')),
                ('ceo', models.CharField(max_length=512, null=True, verbose_name='Руководитель организации')),
                ('company_bin', models.CharField(max_length=12, unique=True, verbose_name='БИН')),
                ('address_ru', models.CharField(max_length=1024, null=True, verbose_name='Адрес организации на русском')),
                ('address_kz', models.CharField(max_length=1024, null=True, verbose_name='Адрес организации на казахском')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Kato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kato_code', models.IntegerField(unique=True, verbose_name='КАТО коде')),
                ('kato_name', models.CharField(max_length=512, verbose_name='КАТО название')),
            ],
            options={
                'db_table': 'kato',
            },
        ),
        migrations.CreateModel(
            name='Kfc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kfc_code', models.IntegerField(unique=True, verbose_name='КФС код')),
                ('kfc_name', models.CharField(max_length=512, verbose_name='КФС название')),
            ],
            options={
                'db_table': 'kfc',
            },
        ),
        migrations.CreateModel(
            name='Krp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('krp_code', models.IntegerField(unique=True, verbose_name='КРП код')),
                ('krp_name', models.CharField(max_length=512, verbose_name='КРП название')),
            ],
            options={
                'db_table': 'krp',
            },
        ),
        migrations.CreateModel(
            name='Kse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kse_code', models.IntegerField(unique=True, verbose_name='КСЕ код')),
                ('kse_name', models.CharField(max_length=512, verbose_name='КСЕ название')),
            ],
            options={
                'db_table': 'kse',
            },
        ),
        migrations.CreateModel(
            name='Oked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oked_code', models.IntegerField(unique=True, verbose_name='ОКЭД код')),
                ('oked_name', models.CharField(max_length=512, verbose_name='ОКЭД название')),
            ],
            options={
                'db_table': 'oked',
            },
        ),
        migrations.CreateModel(
            name='Tnved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код ТН ВЭД')),
                ('name_ru', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Наименование ТН ВЭД')),
            ],
            options={
                'verbose_name': 'ТН ВЭД',
                'verbose_name_plural': 'ТН ВЭД',
                'db_table': 'tnved',
            },
        ),
        migrations.CreateModel(
            name='CompanyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО')),
                ('position', models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('is_mailing_contact', models.BooleanField(default=False, verbose_name='Использовать для рассылок')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='companies.company', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Контакт компании',
                'verbose_name_plural': 'Контакты компаний',
                'db_table': 'company_contacts',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='kato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='companies.kato', verbose_name='КАТО'),
        ),
        migrations.AddField(
            model_name='company',
            name='kfc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='companies.kfc', verbose_name='КФС'),
        ),
        migrations.AddField(
            model_name='company',
            name='krp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='companies.krp', verbose_name='КРП'),
        ),
        migrations.AddField(
            model_name='company',
            name='kse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='companies.kse', verbose_name='КСЕ'),
        ),
        migrations.AddField(
            model_name='company',
            name='primary_oked',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='primary_oked', to='companies.oked', verbose_name='ОКЭД'),
        ),
        migrations.AddField(
            model_name='company',
            name='secondary_okeds',
            field=models.ManyToManyField(related_name='secondary_okeds', to='companies.oked'),
        ),
        migrations.CreateModel(
            name='CompanyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='companies.company', verbose_name='Организация')),
                ('tnved', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='companies.tnved', verbose_name='ТН ВЭД')),
            ],
            options={
                'verbose_name': 'Продукция компании',
                'verbose_name_plural': 'Продукция компаний',
                'db_table': 'company_products',
                'unique_together': {('company', 'tnved')},
            },
        ),
    ]
