# Generated by Django 6.0 on 2025-12-24 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Название организации на русском')),
                ('name_kz', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Название организации на казахском')),
                ('register_date', models.DateField(null=True, verbose_name='Время создания организации')),
                ('ceo', models.CharField(max_length=512, null=True, verbose_name='Руководитель организации')),
                ('company_bin', models.CharField(max_length=12, unique=True, verbose_name='БИН')),
                ('address', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Адрес организации на русском')),
                ('phone_number', models.CharField(blank=True, max_length=128, null=True, verbose_name='Номер телефона')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Электронная почта')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Компании',
                'verbose_name_plural': 'Компании',
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='CompanyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО')),
                ('position', models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('is_mailing_contact', models.BooleanField(default=False, verbose_name='Использовать для рассылок')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
            ],
            options={
                'verbose_name': 'Контакт компании',
                'verbose_name_plural': 'Контакты компаний',
                'db_table': 'company_contacts',
            },
        ),
    ]
