# Generated by Django 6.0 on 2025-12-24 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('dictionaries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dictionaries.industry'),
        ),
        migrations.AddField(
            model_name='company',
            name='kato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dictionaries.kato', verbose_name='КАТО'),
        ),
        migrations.AddField(
            model_name='company',
            name='kfc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dictionaries.kfc', verbose_name='КФС'),
        ),
        migrations.AddField(
            model_name='company',
            name='krp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dictionaries.krp', verbose_name='КРП'),
        ),
        migrations.AddField(
            model_name='company',
            name='kse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dictionaries.kse', verbose_name='КСЕ'),
        ),
        migrations.AddField(
            model_name='company',
            name='primary_oked',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='primary_oked', to='dictionaries.oked', verbose_name='ОКЭД'),
        ),
        migrations.AddField(
            model_name='company',
            name='product',
            field=models.ManyToManyField(blank=True, to='dictionaries.product'),
        ),
        migrations.AddField(
            model_name='company',
            name='secondary_okeds',
            field=models.ManyToManyField(related_name='secondary_okeds', to='dictionaries.oked'),
        ),
        migrations.AddField(
            model_name='companycontact',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='companies.company', verbose_name='Организация'),
        ),
    ]
