# Generated by Django 6.0 on 2025-12-23 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Отрасль',
                'verbose_name_plural': 'Отрасли',
                'db_table': 'industries',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Тип товара',
                'verbose_name_plural': 'Типы товаров',
                'db_table': 'product',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.CharField(max_length=255, null=True, verbose_name='Электронная почта'),
        ),
        migrations.AddField(
            model_name='company',
            name='phone_number',
            field=models.CharField(max_length=128, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='companies.industry'),
        ),
        migrations.AddField(
            model_name='company',
            name='product',
            field=models.ManyToManyField(blank=True, to='companies.product'),
        ),
    ]
