# Generated by Django 6.0 on 2025-12-24 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_industry_product_company_email_company_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Компании', 'verbose_name_plural': 'Компании'},
        ),
        migrations.RemoveField(
            model_name='company',
            name='address_kz',
        ),
        migrations.RemoveField(
            model_name='company',
            name='address_ru',
        ),
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Адрес организации на русском'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='companies.industry'),
        ),
        migrations.AlterField(
            model_name='company',
            name='kato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='companies.kato', verbose_name='КАТО'),
        ),
        migrations.AlterField(
            model_name='company',
            name='kfc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='companies.kfc', verbose_name='КФС'),
        ),
        migrations.AlterField(
            model_name='company',
            name='krp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='companies.krp', verbose_name='КРП'),
        ),
        migrations.AlterField(
            model_name='company',
            name='kse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='companies.kse', verbose_name='КСЕ'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name_kz',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Название организации на казахском'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name_ru',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Название организации на русском'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone_number',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='company',
            name='primary_oked',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='primary_oked', to='companies.oked', verbose_name='ОКЭД'),
        ),
    ]
