# Generated by Django 6.0 on 2025-12-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='pay_nds',
            field=models.BooleanField(null=True, verbose_name='Плательщик НДС'),
        ),
        migrations.AddField(
            model_name='company',
            name='tax_risk',
            field=models.CharField(max_length=32, null=True, verbose_name='Степень риска налогоплательщика'),
        ),
    ]
