# Generated by Django 6.0 on 2026-01-05 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_pay_nds_company_tax_risk'),
        ('dictionaries', '0003_alter_industry_options_kato_parent_kse_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='ceo',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Руководитель организации'),
        ),
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dictionaries.industry'),
        ),
        migrations.AlterField(
            model_name='company',
            name='register_date',
            field=models.DateField(blank=True, null=True, verbose_name='Время создания организации'),
        ),
        migrations.AlterField(
            model_name='company',
            name='secondary_okeds',
            field=models.ManyToManyField(blank=True, related_name='secondary_okeds', to='dictionaries.oked'),
        ),
    ]
