# Generated by Django 6.0 on 2026-01-05 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_company_ceo_alter_company_industry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companycontact',
            name='email',
        ),
        migrations.RemoveField(
            model_name='companycontact',
            name='phone',
        ),
        migrations.AlterField(
            model_name='companycontact',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companycontact',
            name='is_mailing_contact',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='companycontact',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companycontact',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ContactEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('is_primary', models.BooleanField(default=False)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='companies.companycontact')),
            ],
        ),
        migrations.CreateModel(
            name='ContactPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='companies.companycontact')),
            ],
        ),
    ]
