# Generated by Django 6.0 on 2026-01-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_remove_companycontact_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companycontact',
            name='is_mailing_contact',
        ),
        migrations.AddField(
            model_name='contactemail',
            name='is_mailing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactphone',
            name='is_mailing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='contactemail',
            constraint=models.UniqueConstraint(fields=('contact', 'email'), name='uniq_contact_email'),
        ),
        migrations.AddConstraint(
            model_name='contactphone',
            constraint=models.UniqueConstraint(fields=('contact', 'phone'), name='uniq_contact_phone'),
        ),
    ]
