# Generated by Django 6.0 on 2026-01-12 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_remove_companycontact_is_mailing_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='email',
        ),
        migrations.RemoveField(
            model_name='company',
            name='phone_number',
        ),
    ]
