# Generated by Django 6.0 on 2026-01-12 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_remove_company_email_remove_company_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название сертификата')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='companies.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Сертификат компании',
                'verbose_name_plural': 'Сертификаты компаний',
                'db_table': 'company_certificates',
            },
        ),
    ]
