# Generated by Django 6.0 on 2026-01-12 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_companycertificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название сертификата')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
                'db_table': 'certificates',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='certificates',
            field=models.ManyToManyField(blank=True, related_name='companies', to='companies.certificate', verbose_name='Сертификаты'),
        ),
        migrations.DeleteModel(
            name='CompanyCertificate',
        ),
    ]
