# Generated by Django 6.0 on 2026-01-19 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_certificate_company_certificates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='product_description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание продукции'),
        ),
    ]
