# Generated by Django 6.0 on 2026-01-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_company_product_description'),
        ('dictionaries', '0008_delete_companyproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='tnveds',
            field=models.ManyToManyField(blank=True, related_name='companies', to='dictionaries.tnved', verbose_name='ТН ВЭД'),
        ),
    ]
