# Generated by Django 6.0 on 2026-01-20 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_company_tnveds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactphone',
            name='phone',
            field=models.CharField(max_length=40),
        ),
    ]
