# Generated by Django 6.0 on 2025-12-24 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название программы')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание программы')),
            ],
            options={
                'verbose_name': 'Программа',
                'verbose_name_plural': 'Программы',
                'db_table': 'programs',
            },
        ),
        migrations.CreateModel(
            name='ProgramParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Год участия')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_participations', to='companies.company', verbose_name='Организация')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='programs.program', verbose_name='Программа')),
            ],
            options={
                'verbose_name': 'Участие в программе',
                'verbose_name_plural': 'Участие в программах',
                'db_table': 'program_participation',
                'unique_together': {('company', 'program', 'year')},
            },
        ),
    ]
