# Generated by Django 6.0 on 2026-02-05 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0012_alter_contactphone_phone'),
        ('dictionaries', '0009_country'),
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccelerationParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год участия')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceleration_participations', to='companies.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Участие в программе «Акселерация»',
                'verbose_name_plural': 'Участие в программе «Акселерация»',
                'db_table': 'acceleration_participation',
                'unique_together': {('company', 'year')},
            },
        ),
        migrations.CreateModel(
            name='TEMParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год проведения')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_missions', to='companies.company', verbose_name='Компания')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trade_missions', to='dictionaries.country', verbose_name='Страна ТЭМ')),
            ],
            options={
                'verbose_name': 'Торгово-экономическая миссия',
                'verbose_name_plural': 'Торгово-экономические миссии',
                'db_table': 'trade_economic_mission',
                'unique_together': {('company', 'year', 'country')},
            },
        ),
    ]
