# Generated by Django 6.0 on 2025-12-24 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Отрасль',
                'verbose_name_plural': 'Отрасли',
                'db_table': 'industries',
            },
        ),
        migrations.CreateModel(
            name='Kato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kato_code', models.CharField(max_length=12, unique=True, verbose_name='Код КАТО')),
                ('kato_name', models.CharField(max_length=512, verbose_name='КАТО название')),
            ],
            options={
                'verbose_name': 'Административно-территориальные объекты (КАТО)',
                'verbose_name_plural': 'Административно-территориальные объекты (КАТО)',
                'db_table': 'kato',
            },
        ),
        migrations.CreateModel(
            name='Kfc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kfc_code', models.CharField(max_length=10, unique=True, verbose_name='Код КФС')),
                ('kfc_name', models.CharField(max_length=512, verbose_name='КФС название')),
            ],
            options={
                'verbose_name': 'Форма собственности',
                'verbose_name_plural': 'Форма собственности',
                'db_table': 'kfc',
            },
        ),
        migrations.CreateModel(
            name='Krp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('krp_code', models.CharField(max_length=10, unique=True, verbose_name='Код КРП')),
                ('krp_name', models.CharField(max_length=512, verbose_name='КРП название')),
            ],
            options={
                'verbose_name': 'Размер предприятия',
                'verbose_name_plural': 'Размер предприятия',
                'db_table': 'krp',
            },
        ),
        migrations.CreateModel(
            name='Kse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kse_code', models.CharField(max_length=10, unique=True, verbose_name='Код КСЕ')),
                ('kse_name', models.CharField(max_length=512, verbose_name='КСЕ название')),
            ],
            options={
                'verbose_name': 'Экономические сектора',
                'verbose_name_plural': 'Экономические сектора',
                'db_table': 'kse',
            },
        ),
        migrations.CreateModel(
            name='Oked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oked_code', models.CharField(max_length=10, unique=True, verbose_name='Код ОКЭД')),
                ('oked_name', models.CharField(max_length=512, verbose_name='ОКЭД название')),
            ],
            options={
                'verbose_name': 'Виды экономической деятельности (ОКЭД)',
                'verbose_name_plural': 'Виды экономической деятельности (ОКЭД)',
                'db_table': 'oked',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Тип товара',
                'verbose_name_plural': 'Типы товаров',
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Tnved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tn_ved_code', models.CharField(max_length=10, unique=True, verbose_name='Код ТН ВЭД')),
                ('tn_ved_name', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Наименование ТН ВЭД')),
            ],
            options={
                'verbose_name': 'ТН ВЭДы',
                'verbose_name_plural': 'ТН ВЭДы',
                'db_table': 'tnved',
            },
        ),
        migrations.CreateModel(
            name='CompanyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='companies.company', verbose_name='Организация')),
                ('tnved', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='dictionaries.tnved', verbose_name='ТН ВЭД')),
            ],
            options={
                'verbose_name': 'Продукция компании',
                'verbose_name_plural': 'Продукция компаний',
                'db_table': 'company_products',
                'unique_together': {('company', 'tnved')},
            },
        ),
    ]
