# Generated by Django 6.0 on 2026-01-05 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0002_industry_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='industry',
            options={'ordering': ('name',), 'verbose_name': 'Отрасль', 'verbose_name_plural': 'Отрасли'},
        ),
        migrations.AddField(
            model_name='kato',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='dictionaries.kato', verbose_name='Родительский КАТО'),
        ),
        migrations.AddField(
            model_name='kse',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='dictionaries.kse', verbose_name='Родительский сектор'),
        ),
        migrations.AddField(
            model_name='oked',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='dictionaries.oked', verbose_name='Родительский ОКЭД'),
        ),
    ]
