# Generated by Django 6.0 on 2026-01-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0003_alter_industry_options_kato_parent_kse_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kato',
            name='path',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=512, null=True, verbose_name='Путь КАТО'),
        ),
    ]
