# Generated by Django 6.0 on 2026-01-12 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0004_kato_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='oked',
            name='path',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=512, null=True, verbose_name='Путь ОКЭД'),
        ),
    ]
