# Generated by Django 6.0 on 2026-01-12 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0005_oked_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='krp',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='dictionaries.krp', verbose_name='Родительский КРП'),
        ),
        migrations.AddField(
            model_name='krp',
            name='path',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=512, null=True, verbose_name='Путь КРП'),
        ),
    ]
