# Generated by Django 6.0 on 2026-01-14 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0006_krp_parent_krp_path'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['path'], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AddField(
            model_name='product',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='dictionaries.product', verbose_name='Родительский продукт'),
        ),
        migrations.AddField(
            model_name='product',
            name='path',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=512, null=True, verbose_name='Путь продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Наименование продукта'),
        ),
    ]
