# Generated by Django 6.0 on 2026-01-19 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0007_alter_product_options_product_parent_product_path_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyProduct',
        ),
    ]
